In [1]:
import tensorflow

In [2]:
print(tensorflow.__version__)

2.14.0


In [3]:
from tensorflow.keras.datasets import mnist

In [4]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [5]:
len(train_images)

60000

In [6]:
len(train_labels)

60000

In [7]:
len(test_images)

10000

In [8]:
len(test_labels)

10000

In [9]:
train_images[0]  #it will tell us the 1st images of our training 

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [10]:
train_images[0].shape # it will tell us the shape of our 1st image that is 28 rows and 28 columns

(28, 28)

In [11]:
train_images.shape

(60000, 28, 28)

In [12]:
train_labels[0] # it will tell us the 1st train image label that is 5

5

In [13]:
# in this cell we will prepare the network model architecture 
from tensorflow.keras import models
from tensorflow.keras import layers

In [14]:
model= models.Sequential()

model.add(layers.Dense(512, activation='relu', input_shape=(784,)))
model.add(layers.Dense(10, activation='softmax'))

In [15]:
# Now we will compile our model 
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [16]:
# Preparing the image data
train_images = train_images.reshape((60000, 784))
train_images = train_images.astype('float32') / 255

In [17]:
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [18]:
#Preparing the labels
from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [89]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 5s 11ms/step - loss: 0.0068 - accuracy: 0.9986
Epoch 2/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0053 - accuracy: 0.9990
Epoch 3/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0037 - accuracy: 0.9992
Epoch 4/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0027 - accuracy: 0.9996
Epoch 5/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0014 - accuracy: 0.9999


In [90]:
#testing
test_loss,test_acc = model.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

313/313 [==============================] - 1s 4ms/step - loss: 0.0614 - accuracy: 0.9836
test_acc: 0.9836000204086304


In [91]:
print('test_loss:', test_loss)

test_loss: 0.06140598654747009


In [92]:
import tensorflow
from tensorflow.keras.preprocessing import image

In [103]:
img=image.load_img("pic1.png", target_size=(28,28), grayscale=True, color_mode = "grayscale")

In [104]:
img

In [105]:
img_arr = tensorflow.keras.utils.img_to_array(img)

In [106]:
img_arr.shape

(28, 28, 1)

In [107]:
img_arr = img_arr.reshape((1,784))


In [108]:
img_arr

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   6.,
         63., 156., 159., 195., 177., 177., 130.,  63.,  60.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   4., 101., 220., 

In [109]:
type(img_arr)

numpy.ndarray

In [110]:
img_arr.shape

(1, 784)

In [111]:
model.predict(img_arr)


1/1 [==============================] - 0s 37ms/step


array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [112]:
img_arr

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   6.,
         63., 156., 159., 195., 177., 177., 130.,  63.,  60.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   4., 101., 220., 